<?php
/**
 * Copyright 2012-2017 Horde LLC (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (GPL). If you
 * did not receive this file, see http://www.horde.org/licenses/gpl.
 *
 * @category  Horde
 * @copyright 2012-2017 Horde LLC
 * @license   http://www.horde.org/licenses/gpl GPL
 * @package   IMP
 */

class IMP_Ajax_Application_Handler_SaveId extends Horde_Core_Ajax_Application_Handler
{
    /**
     * Ajax action: return the reload Url as generated by UI class of Smime
     */
    public function getReload()
    {
        global $vars;
        $ui = new Horde_Core_Prefs_Ui($vars);
        $url = base64_encode($ui->selfUrl()->setRaw(true));
        return $url;
    }

    /**
     * Ajax action: get Identity keys
     */
    public function getIdentityKeys()
    {
        global $injector, $vars;

        // gets the identityID as set by identitykey.js in the second json-argument of horde.doAction
        $identityID = $this->vars->strangeId;

        // get Smime class object
        $smime = $injector->getInstance('IMP_Smime');

        // get default identityID
        $defaultIdentityID = $injector->getInstance('IMP_Identity')->getDefault();

        // if current identity is default identity, warn user to use the smime prefs for id management
        if ($identityID == $defaultIdentityID) {
            $relinkUrl = 'https://horde.dev.local/horde/services/prefs.php?app=imp&group=smime'; // TODO: generate this url dynamically
        }

        // this lists extra keys. Currently this is not supportet
        // $keys = $smime->listAllKeys($prefName = 'smime_private_key', $identityID); // TODO: what about singkeys?
        // \Horde::debug($keys, '/dev/shm/keys', false);

        // Get clickable links for the personal keys saved in the prefs table and return them
        // Loading Smime bas url in order to set links to it
        // TODO: these links need to take care of the specific id of the identity!!
        $smime_url = IMP_Basic_Smime::url();

        if (isset($relinkUrl)) {
            $linkArray['relink'] = '<a href="'.$relinkUrl.'">Please use the SMIME Preferences Page to manage the keys of your standard identity</a>';
        } else {
            $linkArray['viewpublic'] = $smime_url->copy()
            ->add('actionID', 'view_personal_public_key')
            ->link([
                'title' => _('View Personal Public Certificate'),
                'target' => 'view_key',
            ])
            . _('View') . '</a>';
            $linkArray['infos'] = $smime_url->copy()
            ->add('actionID', 'info_personal_public_key')
            ->link([
                'title' => _('Information on Personal Public Certificate'),
                'target' => 'info_key',
            ])
            . _('Details') . '</a>';
        }

        $linkArray = json_encode($linkArray);

        return $linkArray;
    }
}
