<?php
/**
 * Copyright 2012-2017 Horde LLC (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (GPL). If you
 * did not receive this file, see http://www.horde.org/licenses/gpl.
 *
 * @category  Horde
 * @copyright 2012-2017 Horde LLC
 * @license   http://www.horde.org/licenses/gpl GPL
 * @package   IMP
 */

class IMP_Ajax_Application_Handler_SaveId extends Horde_Core_Ajax_Application_Handler
{
    /**
     * Ajax action: return the reload Url as generated by UI class of Smime
     */
    public function getReload()
    {
        global $vars;
        $ui = new Horde_Core_Prefs_Ui($vars);
        $url = base64_encode($ui->selfUrl()->setRaw(true));
        return $url;
    }

    /**
     * Ajax action: get Identity keys
     */
    public function getIdentityKeys()
    {
        global $injector, $vars;

        // gets the identityID as set by identitykey.js in the second json-argument of horde.doAction
        $identityID = $this->vars->strangeId;

        // get Smime class object
        $smime = $injector->getInstance('IMP_Smime');

        // if current identity is the identity with ID 0, warn the user to use the smime prefs url for id management?
        // Note: if one changes the default identity, currently the smime page does not show the keys for that idenity...
        // TODO: if one changes the default idenity all the keys on the smimepage have to change as well!!
        // OR: Dissallow changing the default identity?
        if ($identityID == $defaultIdentityID) {
            $relinkUrl = 'https://horde.dev.local/horde/services/prefs.php?app=imp&group=smime'; // TODO: generate this url dynamically
        }

        // TODO: this lists extra keys from the extra table (should I add the personal keys to this array? They are not in there, because they are in the prefs table...)
        $keys = $smime->listAllKeys($prefName = 'smime_private_key', $identityID); // TODO: what about singkeys?
        // \Horde::debug($keys, '/dev/shm/keys', false);

        // Get clickable links for the personal keys saved in the prefs table and return them
        // Loading Smime bas url in order to set links to it
        // TODO: these links need to take care of the specific id of the identity!!
        $smime_url = IMP_Basic_Smime::url();

        if (isset($relinkUrl)) {
            $linkArray['relink'] = '<a href="'.$relinkUrl.'">Please use the SMIME Preferences Page to manage the keys of your standard identity</a>';
        } else {
            foreach ($keys as $val) {
                $title = 'View Identity Keys';
                $privatelink = $smime_url->copy()->add(['actionID' => 'view_extra_private_keys', 'pkID' => $identityID]);
                $publiclink = $smime_url->copy()->add(['actionID' => 'view_extra_public_keys', 'pkID' => $identityID]);
                $publicInfoLink = $smime_url->copy()->add(['actionID' => 'view_extra_public_info', 'pkID' => $identityID]);
                $linkArray['viewpublic'] = Horde::link($publiclink, $title, null, 'view_key');
                $linkArray['infos'] = Horde::link($publicInfoLink, $title, null, 'info_key');
                $linkArray['viewprivate'] = Horde::link($privatelink, $title, null, 'view_key');
            }

            $linkArray = json_encode($linkArray);

            return $linkArray;
        }
    }
}
